const phones = [
  {
    model: 'Nokia 106',
    colors: 'Dark Grey',
    salesPackage: 'Device Nokia, MicroUSB charger, Charging / data cable, Quick guide',
    picture: '',
    dimension: '',
    networks: 'GSM 900/1800(EU)',
    os: 'S30+',
    variant: 'Dual SIM only',
    cpu: 'MTK 6261D',
    storage: '4MB ROM 4MB RAM integrated in chipset',
    camera: '',
    formFactor: 'ITUT',
    display: '1.8QQVGA ( = 1.77)',
    connectivitySensors: 'Micro USB (USB 2.0), 3.5mm AHJ',
    battery: 'Removable 800 mAh battery',
    talkAndStandby: 'Up to 15.7hrs/21.9days Talk/Standby time',
    audio: 'FM Radio (Headset required)',
    torch: 'Yes',
    dimensions: 'Estimated 112 x 49.5 x 14.4mm',
    simCardType: '2FF (Mini Sim)'
  },
  {
    model: 'Nokia 210',
    colors: 'Charcoal, Red and Grey',
    salesPackage: 'Nokia 210, Nokia Micro USB, charger (550 mAh), Quick start guide, Headset',
    picture: '',
    networks: 'GSM 900/1800',
    os: 'S30+',
    variant: 'Dual SIM only',
    cpu: 'MTK 6260A',
    storage: '16 MB',
    camera: 'VGA',
    formFactor: '',
    display: '2.4” QVGA',
    connectivitySensors: 'Micro USB, 3.5mm AHJ',
    battery: 'Removable BL-5C 1020 mAh battery',
    talkAndStandby: 'Up to 18 hours, Up to 20 days',
    audio: 'FM radio, MP3 player',
    torch: '',
    dimensions: '120.8 x 53.49 x 13.81 mm',
    simCardType: '2FF (Mini Sim)'
  },
  {
    model: 'Nokia 5310',
    colors: 'White and Black',
    salesPackage: 'Device, Battery, Nokia Micro USB charger (550 mAh), Quick guide, Headset',
    picture: '',
    networks: 'GSM 900/1800',
    os: 'S30+',
    variant: '',
    cpu: 'MT6260A',
    storage: '16MB (ROM) + 8MB (RAM); Memory card slot expandable upto 32GB',
    camera: '',
    formFactor: '',
    display: '2.4” QVGA',
    connectivitySensors: 'Micro USB (USB 1.1), 3.5mm',
    battery: 'Removable 1200 mAh battery',
    talkAndStandby: 'Up to 20.7 hours talk time and up to 30 days standby time. (Single SIM). Up to 20.7 hours talk time and up to 22 days standby time (Dual SIM)',
    audio: 'Dual speakers, FM Radio (wired+wireless), MP3/3G2/3GP/AMR player',
    torch: '',
    dimensions: '123.7mm x 52.4mm x 13.1mm',
    simCardType: 'Single SIM / Dual SIM / 2FF'
  },
  {
    model: 'Nokia 3310',
    colors: '',
    salesPackage: 'Nokia 3310 device. Quick start guide. Battery: BL-5C (1200 mAh). Micro-USB Charger. Headset WH-108',
    picture: '',
    networks: '',
    os: '',
    variant: '',
    cpu: '',
    storage: 'MicroSD card support up to 32 GB',
    camera: '2Mpxl camera with LED flash',
    formFactor: '',
    display: '2.4" QVGA (240*320)',
    connectivitySensors: 'micro USB, 3.5mm AV connector, Bluetooth 3.0 with SLAM',
    battery: '',
    talkAndStandby: 'Standby time: up to 25.3 days. Talk time: up to 22.1 hours. MP3 playback up to 51 hours (volume 5). FM radio playback up to 39 hours',
    audio: '',
    torch: 'Yes',
    dimensions: '115.6 x 51.0 x 12.8mm',
    simCardType: 'Dual SIM'
  },
  {
    model: 'Nokia 8110',
    colors: '',
    salesPackage: '',
    picture: '',
    networks: '',
    os: 'KaiOS',
    variant: '',
    cpu: 'CPU MSM8905 Dual Core 1.1 GHz',
    storage: '4GB Internal Storage and RAM 512 MB',
    camera: '2 MP camera with LED flash',
    formFactor: '',
    display: '2.4" curved screen',
    connectivitySensors: '4G',
    battery: '',
    talkAndStandby: 'Standby time (4G) Up to 25 days',
    audio: '3.5mm audio jack',
    torch: '',
    dimensions: '',
    simCardType: ''
  },
  {
    model: 'Nokia 800 Tough',
    colors: 'Black Steel | Desert Sand',
    salesPackage: 'Nokia 800 Tough | Charger | USB Cable | Quick Start Guide',
    picture: '',
    networks: 'LTE Cat 4 - 150Mbps DL/50Mbps UL | VoLTE | VoWiFi',
    os: 'KaiOS',
    variant: '',
    cpu: 'Qualcomm® 205 Mobile Platform',
    storage: '512MB LPDDR3, 4GB eMMC , Micro SD supports (up to 32GB)',
    camera: '2MP + Flash',
    formFactor: '',
    display: '2.4” (6.1 cm) QVGA',
    connectivitySensors: '802.11 b/g/n , Bluetooth 4.1 , GPS/AGPS , FM Radio',
    battery: '2100mAh (Typ.) non-removable',
    talkAndStandby: 'Single Sim: Standby time up to: GSM 43.7 days, 3G 43.0 days, 4G 34.0 days. Talk time up to: GSM 12.5 hours, 3G 14.3 hours, 4G 9.4 hours. Dual Sim: Standby time up to: GSM 36.2 days, 3G 30.4 days, 4G 22.4 days. Talk time up to: GSM 12.5 hours, 3G 14.3 hours, 4G 9.4 hours',
    audio: '3.5mm audio jack',
    torch: 'Yes',
    dimensions: '16.11 x 62.1 x 145.4',
    simCardType: '2 Nano SIM or 1 Nano Sim + SD slot'
  },
  {
    model: 'Nokia 2720 Flip',
    colors: 'Black | Grey',
    salesPackage: '',
    picture: '',
    networks: 'LTE Cat 4 - 150Mbps DL/50Mbps UL | VoLTE2 | VoWi-Fi',
    os: 'KaiOS',
    variant: 'Single SIM and Dual SIM (Nano SIM',
    cpu: 'Qualcomm 205 Mobile Platform',
    storage: 'RAM: 512MB, ROM: 4GB3 + extendable microSD card slot supports up to 32GB',
    camera: '2MP + flash',
    formFactor: '',
    display: '2.8” (7.1 cm) QVGA + 1.3” (3.3 cm) 240x240',
    connectivitySensors: 'Wi-Fi WLAN IEEE 802.11 b/g/n,  Location: GPS/AGPS + GLONASS  Bluetooth® 4.1, A2DP, AVRCP, DUN, FTP, HFP, HID, HSP, MAP, OPP, PBAP, PAN, IOPT  Micro USB (USB 2.0), 3.5mm AHJ HAC (Hearing Aid Compatible)',
    battery: 'Removable BL-6V 1500 mAh',
    talkAndStandby: 'Single Sim: Standby time up to: GSM 27.8 days, 3G 28.9 days, 4G 20.9 days | Talk time up to: GSM 8.9 hours, 3G 10.9 hours, 4G 6.6 hours. Dual Sim: Standby time up to: GSM 19.3 days, 3G 18.2 days, 4G 14.0 days | Talk time up to: GSM 8.9 hours, 3G 10.9 hours, 4G 6.6 hours',
    audio: '',
    torch: 'Yes',
    dimensions: 'Closed: 54.5 mm x 104.8 mm x 18.7 mm Open: 54.5 mm x 192.7 mm x 11.6 mm',
    simCardType: 'Single SIM and Dual SIM (Nano SIM)'
  },
  {
    model: 'Nokia 105',
    colors: '',
    salesPackage: '',
    picture: '',
    networks: 'GSM 900/1800(EU) 850/1900(US)',
    os: 'S30+',
    variant: 'Dual SIM / Single SIM',
    cpu: '',
    storage: '4MB RAM 4MB ROM',
    camera: '',
    formFactor: 'ITUT',
    display: '1.8" QQVGA',
    connectivitySensors: 'Micro USB (USB 2.0), 3.5mm AHJ',
    battery: 'Removable 800 mAh battery',
    talkAndStandby: 'Standby time: Up to 30 days.s Dual SIM Standby time: Up to 21 days. Talk time: Up to 15hrs',
    audio: 'FM Radio',
    torch: '',
    dimensions: '112.0 x 49.45 x 14.4mm',
    simCardType: '2FF (mini SIM)'
  }
];

module.exports = phones;
